### ISSUE TITLE
Scratch Cloud

### ISSUE THREAD

**Issue by hello-smile6** [webdev03/webdev03#4]
It is not helping, the game is being killed within 5 seconds.

**Comment by webdev03** [comment]
https://gist.github.com/webdev03/9ad4ddb57915813b27928133fa080a23

**Comment by webdev03** [comment]
The game is instantly being killed. We'll need so many people to run the script. @hello-smile6 get everyone who can help onboard

**Comment by hello-smile6** [comment]
> The game is instantly being killed. We'll need so many people to run the script. @hello-smile6 get everyone who can help onboard

Create an ATs topic. Get people on the project to create Replit accounts, fork it, and send you the name. Even better, make the script automatically add itself to 9gr's pinger.

**Comment by hello-smile6** [comment]
Got a version with an HTTP server, for Replit deployments.
```
from scratchclient import ScratchSession

import http.server
import socketserver

PORT = 8080
Handler = http.server.SimpleHTTPRequestHandler

with socketserver.TCPServer(("", PORT), Handler) as httpd:
    print("serving at port", PORT)
    httpd.serve_forever()
print("logging in")
import os
session = ScratchSession(os.environ["uname"], os.environ["passw"])
print("connecting to cloud")
cloud1 = session.create_cloud_connection(612229554)
print("connected")
while True:
  cloud1.set_cloud_variable("ONLINE", "28")

# VERSION=11 478790208
```

**Comment by webdev03** [comment]
I'm making a multi-threaded version for even faster changes :)

**Comment by hello-smile6** [comment]
Okay

**Comment by webdev03** [comment]
Updating the gist

**Comment by webdev03** [comment]
OOF, that script makes Scratch quite angry. I've reverted the changes.

**Comment by webdev03** [comment]
I'm going to have to do my work now. See you in 30 minutes. Bye! :smile:

**Comment by webdev03** [comment]
I'm back.

**Comment by webdev03** [comment]
Wow perfect timing - 29 minutes ago

**Comment by hello-smile6** [comment]
> Any solutions? Is beep blooper beep gone?

They aren't on now, but I'm keeping my script on. Could you set up something on your computer to send an HTTP request to my servers every minute? It's scratch-cloud-keepalive-1 and scratch-cloud-keepalive-2 on my replit account.

**Comment by webdev03** [comment]
Just use uptimerobot, and anyways, the script is probably not going to work. I think Bepp Bloop Blop came in the ATs recently too. Up to no good.

**Comment by hello-smile6** [comment]
> Just use uptimerobot, and anyways, the script is probably not going to work. I think Bepp Bloop Blop came in the ATs recently too. Up to no good.

Verified. https://ocular.jeffalo.net/search?q=%2Busername%3A%22boopboop92%22&sort=relevance https://ocular.jeffalo.net/post/5942682

**Comment by hello-smile6** [comment]
> Just use uptimerobot, and anyways, the script is probably not going to work. I think Bepp Bloop Blop came in the ATs recently too. Up to no good.

It will probably work if enough people use it.

**Comment by hello-smile6** [comment]
I have CPMF and MMO covered, by the way.

**Comment by webdev03** [comment]
Hmm

**Comment by hello-smile6** [comment]
> Hmm

People should've caught on. They didn't even give anything that'd do anything.

**Comment by hello-smile6** [comment]
Yet they were using keep_alive scripts.

**Comment by webdev03** [comment]
I hope their account gets banned from using cloud - this is seriously awful. They tricked the ATs to do bad things.

**Comment by webdev03** [comment]
Also why don't you join the ATs studio?

**Comment by hello-smile6** [comment]
> I hope their account gets banned from using cloud - this is seriously awful. They tricked the ATs to do bad things.

Create a topic about it! That'd help. Also, make your script parse a file in the same gist that has a list of variables to enforce, so everyone's running an up-to-date list.

**Comment by webdev03** [comment]
> Also, make your script parse a file in the same gist that has a list of variables to enforce

could be used to detect users of the script

**Comment by hello-smile6** [comment]
> > Also, make your script parse a file in the same gist that has a list of variables to enforce
> 
> could be used to detect users of the script

Good point. Maybe ping griffpatch on youtube and ask them to write a Python client. Then you could make fake players that reply past users' movements. That'd work for the main one, at least. Or you could add a feature that automatically deletes spam comments, in order to mitigate any retaliation in the form of spam comments.

**Comment by webdev03** [comment]
> > > Also, make your script parse a file in the same gist that has a list of variables to enforce
> > 
> > 
> > could be used to detect users of the script
> 
> Good point. Maybe ping griffpatch on youtube and ask them to write a Python client. Then you could make fake players that reply past users' movements. That'd work for the main one, at least. Or you could add a feature that automatically deletes spam comments, in order to mitigate any retaliation in the form of spam comments.

Wait a minute
I have an idea
Let's make a spam comment detector and then give a list of spam and stuff!!!! Just like the one ThioJoe made! I'm getting to work on that.

**Comment by hello-smile6** [comment]
> > > > Also, make your script parse a file in the same gist that has a list of variables to enforce
> > > 
> > > 
> > > could be used to detect users of the script
> > 
> > 
> > Good point. Maybe ping griffpatch on youtube and ask them to write a Python client. Then you could make fake players that reply past users' movements. That'd work for the main one, at least. Or you could add a feature that automatically deletes spam comments, in order to mitigate any retaliation in the form of spam comments.
> 
> Wait a minute I have an idea Let's make a spam comment detector and then give a list of spam and stuff!!!! Just like the one ThioJoe made! I'm getting to work on that.

Is there a Scratch admin who does work with the backend? If so, you could just tell them and get the person banned.

**Comment by webdev03** [comment]
codubee

**Comment by hello-smile6** [comment]
> codubee

Okay, could you tell them?

**Comment by webdev03** [comment]
Contact us would be better

**Comment by hello-smile6** [comment]
> Contact us would be better

Then why not do that?

**Comment by webdev03** [comment]
I'm gonna work on the scratch spam protection

**Comment by hello-smile6** [comment]
> I'm gonna work on the scratch spam protection

Okay. By the way, I ghost-replied to @ScratchAddons on Scratch as a test.

**Comment by hello-smile6** [comment]
@webdev03 I can't get your website to let me sign in.

**Comment by webdev03** [comment]
ScratchDB

**Comment by hello-smile6** [comment]
> ScratchDB

How?

**Comment by webdev03** [comment]
ScratchDB stores data, it doesn't get live data. Wait a few days.

**Comment by hello-smile6** [comment]
@webdev03 It's outdated.

**Comment by hello-smile6** [comment]
Any way to fix it?

**Comment by hello-smile6** [comment]
https://assets.scratch.mit.edu/get_image/.%2E/96f39ca6d3557a70e8028b0e8afe45c1.png LOL

**Comment by hello-smile6** [comment]
Could you create a TurboWarp version? They're dOSing a TurboWarp game.

**Comment by webdev03** [comment]
A turbo warp version? I'll look into that soon.

**Comment by hello-smile6** [comment]
> A turbo warp version? I'll look into that soon.

Specifically, Scratcharia. It's been the `#1` target for hackers for over 6 months. Also, could we use Gitter for communication among those with github accounts? https://gitter.im/

**Comment by webdev03** [comment]
I have heard of gitter. But it's unmoderated.

**Comment by hello-smile6** [comment]
> I have heard of gitter. But it's unmoderated.

As long as we don't mention it on Scratch, shouldn't it be fine? Also, I like the idea of a collaboration repository. Even better, a collaboration org, so people could make clients for different codebases and share them.

**Comment by webdev03** [comment]
Collaboration repository as a monorepo

**Comment by hello-smile6** [comment]
> Collaboration repository as a monorepo

Please not monorepo. If we give someone access so they can maintain a Node version, they don't need access to the Python and HTML parts.

**Comment by webdev03** [comment]
I guess.

**Comment by hello-smile6** [comment]
> I guess.

Make sure you choose a memorable name like NotepadJS.

**Comment by webdev03** [comment]
NotepadJS? That's not a hack prevention group...

**Comment by hello-smile6** [comment]
> NotepadJS? That's not a hack prevention group...

Yes, just choose a memorable name.

**Comment by webdev03** [comment]
Also, by the way, the script also interferes with griffpatch's ability to send out updates.

**Comment by hello-smile6** [comment]
> Also, by the way, the script also interferes with griffpatch's ability to send out updates.

I know, that's an unfortunate side affect. Could you make it shut down when griffpatch is on and restart 1 minute after?

**Comment by webdev03** [comment]
How would we even detect that

**Comment by hello-smile6** [comment]
> How would we even detect that

Maybe watch for a decrease in their message count or them setting a cloud var???

**Comment by webdev03** [comment]
> them setting a cloud var

There's like a 1 second window of detecting that.


> decrease in their message count

griffpatch doesn't even read messages

**Comment by hello-smile6** [comment]
> > them setting a cloud var
> 
> There's like a 1 second window of detecting that.
> 
> > decrease in their message count
> 
> griffpatch doesn't even read messages

Oh. So, there's no way to turn it off? What about setting a var that tells them to open a project and send a message to temporarily turn it off? They'd probably check the log if they couldn't disable it.

**Comment by hello-smile6** [comment]
@webdev03 Is there a gh org yet?

**Comment by webdev03** [comment]
Not yet

**Comment by webdev03** [comment]
I've made a much more friendly version that makes the server not come in cloud logs until the attack has started.

**Comment by hello-smile6** [comment]
> I've made a much more friendly version that makes the server not come in cloud logs until the attack has started.

Nice.

**Comment by webdev03** [comment]
I updated the gist

**Comment by hello-smile6** [comment]
> I updated the gist

Will it start if the value is correct?

**Comment by webdev03** [comment]
If the value is 28 then it will just ignore. If it is not 28 it will set the variable to 28.

**Comment by webdev03** [comment]
If the var is 28 I think it stays quiet until it has changed

**Comment by hello-smile6** [comment]
> If the var is 28 I think it stays quiet until it has changed

How about other projects?

**Comment by webdev03** [comment]
Other projects? Those can be added. But this gist is not scalable.

**Comment by hello-smile6** [comment]
> Other projects? Those can be added. But this gist is not scalable.

Okay, I'll deploy a copy and keep mine running.

**Comment by webdev03** [comment]
I'll make it a monorepo for now. I might make it an org in the future.

**Comment by webdev03** [comment]
Fine, I'll make an org. It's going to be called Meowshield for now

**Comment by webdev03** [comment]
I keep on changing my mind 🤣 I'll decide myself.

**Comment by hello-smile6** [comment]
> Fine, I'll make an org. It's going to be called Meowshield for now

Could I have read access?

**Comment by webdev03** [comment]
I made a repo in my user account for it

**Comment by hello-smile6** [comment]
> I made a repo in my user account for it

Okay.

**Comment by hello-smile6** [comment]
Check gitter. (I see you've used it)
